# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\pytuhsar\Ezapiya\language_option_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 611)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1051, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 510, 1051, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(247, 460, 581, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_english = QtWidgets.QPushButton(self.centralwidget)
        self.btn_english.setGeometry(QtCore.QRect(350, 76, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_english.setFont(font)
        self.btn_english.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_english.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_english.setObjectName("btn_english")
        self.btn_hindi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hindi.setGeometry(QtCore.QRect(645, 78, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_hindi.setFont(font)
        self.btn_hindi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_hindi.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_hindi.setObjectName("btn_hindi")
        self.btn_marathi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_marathi.setGeometry(QtCore.QRect(500, 78, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_marathi.setFont(font)
        self.btn_marathi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_marathi.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_marathi.setObjectName("btn_marathi")
        self.btn_font = QtWidgets.QPushButton(self.centralwidget)
        self.btn_font.setGeometry(QtCore.QRect(350, 191, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_font.setFont(font)
        self.btn_font.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_font.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_font.setObjectName("btn_font")
        self.label_girl = QtWidgets.QLabel(self.centralwidget)
        self.label_girl.setGeometry(QtCore.QRect(830, 60, 181, 301))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_girl.setFont(font)
        self.label_girl.setText("")
        self.label_girl.setObjectName("label_girl")
        self.label_girl_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_girl_2.setGeometry(QtCore.QRect(90, 50, 221, 401))
        self.label_girl_2.setText("")
        self.label_girl_2.setObjectName("label_girl_2")
        self.btn_about_us = QtWidgets.QPushButton(self.centralwidget)
        self.btn_about_us.setGeometry(QtCore.QRect(501, 310, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_about_us.setFont(font)
        self.btn_about_us.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_about_us.setObjectName("btn_about_us")
        self.btn_punjabi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_punjabi.setGeometry(QtCore.QRect(502, 190, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_punjabi.setFont(font)
        self.btn_punjabi.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_punjabi.setObjectName("btn_punjabi")
        self.btn_gujarti = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gujarti.setGeometry(QtCore.QRect(650, 191, 131, 101))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gujarti.setFont(font)
        self.btn_gujarti.setStyleSheet("border-top-right-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 0, 110);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"")
        self.btn_gujarti.setObjectName("btn_gujarti")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ezapiya Typing Master"))
        self.label_2.setText(_translate("MainWindow", "EZAPIA TYPING MASTER. POWERED BY Ezapiya Software Research And Development LLP."))
        self.label_3.setText(_translate("MainWindow", "Visit our Website: www.ezapiya.com Contact Details +919373552952 "))
        self.btn_english.setText(_translate("MainWindow", "ENGLISH"))
        self.btn_hindi.setText(_translate("MainWindow", "HINDI"))
        self.btn_marathi.setText(_translate("MainWindow", "MARATHI"))
        self.btn_font.setText(_translate("MainWindow", "Programming \n"
"font "))
        self.btn_about_us.setText(_translate("MainWindow", "ABOUT US"))
        self.btn_punjabi.setText(_translate("MainWindow", "Panjabi"))
        self.btn_gujarti.setText(_translate("MainWindow", "Gujrati"))
